### ISSUE TITLE
little error in Dockerfile

### ISSUE THREAD

**Issue by gleruzh** [ThelonKarrde/phabricator-docker#2]
normal string 22 in the Docker file is (error in **available**)
`COPY ./configs/nginx-ph.conf /etc/nginx/sites-available/phabricator.conf`

But the image is not OK because of the error too.

**Comment by gleruzh** [comment]
the same error string 24.
Normal string:
`RUN ln -s /etc/nginx/sites-available/phabricator.conf /etc/nginx/sites-enabled/phabricator.conf`

**Comment by ThelonKarrde** [comment]
Thanks for highlighting! Fixed 👍
