### ISSUE TITLE
"rm -rf /var/cache/apt" later does not do anything

### ISSUE THREAD

**Issue by Zocker1999NET** [ThelonKarrde/phabricator-docker#3]
Reason: Removing files after Docker has cached them up does not working.

See, with every `RUN` directive in a Dockerfile, Docker does create a new layer for an enhanced caching mechanism, so later steps can be changed without re-downloading packages installed on earlier stages. The command `rm -rf /var/cache/apt` at the end so does only result in a *deleted* marker on the latest layer, while the earlier layer still contains the cached files and so you and others must download them or keep them.

You can fix this by adding the command using `&&` at the end of your `apt install` containing `RUN` directive.

BTW: thanks for pushing this online, as this is one of the best Phabricator Docker setups I saw while searching for inspiration/tips for my own setup.

**Comment by ThelonKarrde** [comment]
Thanks for highlighting! Make sense about cache.. I will update it sometime soon :)

**Comment by ThelonKarrde** [comment]
Updated 👍 
https://github.com/ThelonKarrde/phabricator-docker/pull/4
